# Generated by Django 3.2.7 on 2021-11-28 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Val',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(db_index=True, max_length=240)),
            ],
        ),
        migrations.RenameModel(
            old_name='Dicty',
            new_name='key',
        ),
        migrations.DeleteModel(
            name='KeyVal',
        ),
        migrations.AddField(
            model_name='val',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convert.key'),
        ),
    ]
