# Generated by Django 3.2.7 on 2021-11-29 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0002_auto_20211128_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124)),
                ('number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='convert.number')),
            ],
        ),
        migrations.CreateModel(
            name='words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convert.number')),
            ],
        ),
        migrations.RemoveField(
            model_name='val',
            name='key',
        ),
        migrations.DeleteModel(
            name='key',
        ),
        migrations.DeleteModel(
            name='Val',
        ),
        migrations.AddField(
            model_name='person',
            name='words',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='convert.words'),
        ),
    ]
